BACK/VAB/Userprofile/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from Userprofile import views

app_name = 'Userprofile'

urlpatterns = [
    path('', views.loadHomepage, name='loadHomepage'),
    path('register/', views.register, name='register'),
    path('login/', views.userlogin, name='login'),
    path('Userprofile/<int:id>/profile/', views.profile, name='profile'),
    path('Userprofile/<int:id>/profile/update/', views.profile_update, name='profile_update'),
    path('Userprofile/<int:id>/pwd_change/', views.pwd_change, name='pwd_change'),
    path('logout/', views.userlogout, name='logout'),
    path('registerajax/',views.registerajax,name='registerajax'),
    path('checkusers/',views.checkusers,name='checkusers'),
    path('checkusers_login/',views.checkusers_login,name='checkusers_login'),
    path('checkemail/',views.checkemail,name='checkemail'),
    path('checkpwd/',views.checkpwd,name='checkpwd'),
    path('checkpwd_login/', views.checkpwd_login, name='checkpwd_login'),
]

BACK/VAB/VAB/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
import notifications.urls

urlpatterns = [
    # 用户管理
    path('admin/', admin.site.urls),

    # 图书管理
    path('book/', include('Books.urls')),

    # 视频管理
    path('video/',include('Videos.urls')),
    
    # 用户个人信息
    path('',include('Userprofile.urls')),

    # 评论管理
    path('comment/',include('comment.urls')),

    # 帖子管理
    path('article/',include('article.urls')),

    # 通知信息
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),

    path('notice/',include('notice.urls',namespace='notice')),

    # 小组信息
    path('group/',include('Usergroup.urls',namespace='group')),

    # 举报
    path('report/',include('report.urls',namespace='report')),

    # 申请
    path('ask/',include('askManage.urls',namespace='ask')),

    # 话题
    path('topic/',include('topic.urls',namespace='topic')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BACK/VAB/report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('report-Bookcomment/<int:id>/',views.RBookComment,name='report_Bookcomment'),
    path('report-Videocomment/<int:id>/',views.RVideoComment,name='report_Videocomment'),
    path('report-Articlecomment/<int:id>/',views.RArticleComment,name='report_Articlecomment'),
    path('allMyreport',views.LookAllMyReport,name='allMyreport'),
    path('needhandle',views.needhandleReport,name='needHandle'),
    path('refuse-bookreport/<int:id>/',views.refusebookreport,name='refuseBR'),
    path('refuse-videoreport/<int:id>/',views.refusevideoreport,name='refuseVR'),
    path('refuse-articlereport/<int:id>/',views.refusearticlereport,name='refuseAR'),
    path('handle-bookreport/<int:id>/',views.handlebookreport,name='handleBR'),
    path('handle-videoreport/<int:id>/',views.handlevideoreport,name='handleVR'),
    path('handle-articlereport/<int:id>/',views.handlearticlereport,name='handleAR'),
]

BACK/VAB/report/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from Books.models import Book
from Videos.models import Video
from article.models import Article
from comment.models import BookComment,ArticleComment,VideoComment

# 举报图书评论
class BookCommentReport(models.Model):
    reporter = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='BookcommentReport'
    )

    Administrator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='BookcommentAdministrator',
    )

    bookcomment = models.ForeignKey(
        BookComment,
        on_delete=models.CASCADE,
        related_name='BookcommentReport'
    )

    reason = models.TextField(
        max_length=100
    )

    state = models.IntegerField(default=0)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.reason


# 举报影视评论
class VideoCommentReport(models.Model):
    reporter = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='VideocommentReport'
    )

    Administrator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='VideocommentAdministrator',
    )

    videocomment = models.ForeignKey(
        VideoComment,
        on_delete=models.CASCADE,
        related_name='VideocommentReport'
    )

    reason = models.TextField(
        max_length=100
    )

    state = models.IntegerField(default=0)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.reason


# 举报帖子评论
class ArticleCommentReport(models.Model):
    reporter = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='ArticlecommentReport'
    )

    Administrator = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='ArticlecommentAdministrator',
    )

    articlecomment = models.ForeignKey(
        ArticleComment,
        on_delete=models.CASCADE,
        related_name='ArticlecommentReport'
    )

    reason = models.TextField(
        max_length=100
    )

    state = models.IntegerField(default=0)
    created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return self.reason

BACK/VAB/report/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404, HttpResponse, redirect
from django.http import HttpResponseRedirect

# 方法装饰器
from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.contrib.auth.models import User

# 导入所需要的模型
from comment.models import BookComment,VideoComment,ArticleComment
from Books.models import Book
from article.models import Article
from Videos.models import Video

from .models import VideoCommentReport,BookCommentReport,ArticleCommentReport
from .form import BookCommentReportForm,VideoCommentReportForm,ArticleCommentReportForm

# 发起举报
def RBookComment(request,id):
    if request.method == "POST":
        reportbookcomment_form = BookCommentReportForm(data=request.POST)
        if reportbookcomment_form.is_valid():
            reason = reportbookcomment_form.cleaned_data['reason']
            aBookreport = BookCommentReport.objects.create(
                reporter=request.user,
                Administrator=User.objects.filter(is_superuser=1).first(),
                bookcomment=BookComment.objects.get(id=id),
                reason=reason
            )
            return redirect("Bookdetail",id=BookComment.objects.get(id=id).book.id)
        else:
            return HttpResponse("举报生成错误")
    else:
        bookcomment = BookComment.objects.get(id=id)
        reportform = BookCommentReportForm()
        context = {'reportform':reportform,'comment':bookcomment}
        return render(request,'report/bookreport.html',context)

def RVideoComment(request,id):
    if request.method == "POST":
        reportvideocomment_form = VideoCommentReportForm(data=request.POST)
        if reportvideocomment_form.is_valid():
            reason = reportvideocomment_form.cleaned_data['reason']
            aVideoreport = VideoCommentReport.objects.create(
                reporter=request.user,
                Administrator=User.objects.filter(is_superuser=1).first(),
                videocomment=VideoComment.objects.get(id=id),
                reason=reason
            )
            return redirect("Videodetail",id=VideoComment.objects.get(id=id).video.id)
        else:
            return HttpResponse("举报生成错误")
    else:
        videocomment = VideoComment.objects.get(id=id)
        reportform = VideoCommentReportForm()
        context = {'reportform': reportform,'comment':videocomment}
        return render(request, 'report/videoreport.html', context)

def RArticleComment(request,id):
    if request.method == "POST":
        reportarticlecomment_form = ArticleCommentReportForm(data=request.POST)

        if reportarticlecomment_form.is_valid():
            reason = reportarticlecomment_form.cleaned_data['reason']
            article = ArticleComment.objects.get(id=id).article
            aArticlereport = ArticleCommentReport.objects.create(
                reporter=request.user,
                Administrator=User.objects.filter(is_superuser=1).first(),
                articlecomment=ArticleComment.objects.get(id=id),
                reason=reason
            )
            return redirect("ArticleDetail",id=article.id)
        else:
            return HttpResponse("举报生成错误")
    else:
        articlecomment = ArticleComment.objects.get(id=id)
        reportform = ArticleCommentReportForm()
        context = {'reportform': reportform,'comment':articlecomment}
        return render(request, 'report/articlereport.html', context)

def LookAllMyReport(request):
    allBookReport = BookCommentReport.objects.filter(reporter=request.user)
    allVideoReport = VideoCommentReport.objects.filter(reporter=request.user)
    allArticleReport = ArticleCommentReport.objects.filter(reporter=request.user)
    context = {'allBookReport':allBookReport,'allVideoReport':allVideoReport,'allArticleReport':allArticleReport}
    return render(request,'report/allMyreport.html',context)

def needhandleReport(request):
    allBookReport = BookCommentReport.objects.all()
    allVideoReport = VideoCommentReport.objects.all()
    allArticleReport = ArticleCommentReport.objects.all()
    context = {'allBookReport': allBookReport, 'allVideoReport': allVideoReport, 'allArticleReport': allArticleReport}
    return render(request, 'report/handlereport.html',context)

def refusebookreport(request,id):
    bookreport = BookCommentReport.objects.get(id=id)
    bookreport.state = 1
    bookreport.save()
    return redirect('report:needHandle')

def handlebookreport(request,id):
    bookreport = BookCommentReport.objects.get(id=id)
    bookreport.state = 2
    bookreport.save()
    bookcomment = BookComment.objects.get(id=bookreport.bookcomment.id)
    bookcomment.delete()
    return redirect('report:needHandle')

def refusevideoreport(request,id):
    videoreport = VideoCommentReport.objects.get(id=id)
    videoreport.state = 1
    videoreport.save()
    return redirect('report:needHandle')

def handlevideoreport(request,id):
    videoreport = VideoCommentReport.objects.get(id=id)
    videoreport.state = 2
    videoreport.save()
    videocomment = VideoComment.objects.get(id=videoreport.videocomment.id)
    videocomment.delete()
    return redirect('report:needHandle')

def refusearticlereport(request,id):
    articlereport = ArticleCommentReport.objects.get(id=id)
    articlereport.state = 1
    articlereport.save()
    return redirect('report:needHandle')

def handlearticlereport(request,id):
    articlereport = ArticleCommentReport.objects.get(id=id)
    articlereport.state = 2
    articlereport.save()
    articlecomment = ArticleComment.objects.get(id=articlereport.articlecomment.id)
    articlecomment.canbeseen = False
    articlecomment.save()
    return redirect('report:needHandle')

BACK/VAB/templates/report/articlereport.html
{% load static %}
{% include 'topbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>举报</title>

    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
    <link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/topbar_style.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/reportpage.css' %}">
    <style type="text/css">
        .wechat:hover .qrcode {
            width: 120px;
            height: auto;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(255, 99, 71, 0.5);
        }

        .qrcode {
            width: 0px;
        }

        .wechat:hover .wechat-img {
            padding-left: 40px;
        }
    </style>
    <script>
        window.onload = function () {
            var inp=document.getElementById("reason");
            var btn=document.getElementById("lastbtn");
            btn.onclick = function () {
                if (inp.value.length<15) {
                    alert("字数最少15个字！");
                }
                else
                    alert("提交成功！");
            };
        };
    </script>
</head>

<body>
    <header>
        <div class="topbook-wrap">
            <div class="bookimg iconfont">&#xe711; </div>
            <div class="bookicnline"></div>
            <div class="zi">VAB举报</div>

            <div class="find-wrap">
                <a href="{% url 'report:allMyreport' %}" class="jubaonotea">
                    <div class="jubaonote">我的举报记录</div>
                </a>
            </div>
        </div>
    </header>
    <main>
        <div class="jubaocontaincon" style="margin-top: 10px;height: 300px;">
            <div class="jubaocontain1" style="height: 20px;">
                举报地址：<a href="{% url 'ArticleDetail' comment.article.id %}" style="margin-top: -60px;margin-left: 100px">{{ comment.article.title }}的评论</a>
            </div>
            <div class="jubaocontain2">
                您要举报的评论为：
                <div style="margin-left: 10px;border: 1px solid red;height: auto;width: auto;border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;border-top-left-radius: 10px;border-top-right-radius: 10px">
                    <div style="margin-left: 20px">{{ comment.body|safe }}</div>
                </div>
                评论者：<a href="{% url 'Userprofile:profile' comment.user.id %}" style="margin-top: -60px;margin-left: 70px;height: 10px;width: 10px;color: #ff998c;font-family:JetBrains Mono">{{ comment.user.username }}</a><br>
                评论时间：<font face="Jetbrains Mono" color="#ff6347">{{ comment.created }}</font>
            </div>
        </div>
        <hr>
        <div class="jubaodiscrcon" >
            <form method="post">
                {% csrf_token %}
                <div class="jubaodiscr">问题描述</div>
                <div class="jubaodiscrinp">
                    <input type="text" class="form-control" placeholder="请输入举报理由(不少于15个字)" id="reason" name="reason">
                </div>
                <div class="jubaodiscrinp1">
                    输入你的邮箱 <input type="email" class="form-control" id="exampleInputEmail1" placeholder="{{ user.email }}" style="font-family: JetBrains Mono">
                </div>
                <div class="jubaodiscrinp1">
                    输入你的电话 <input type="text" class="form-control" placeholder="联系电话">
                </div>
                <button type="submit" class="btn btn-outline-danger" id="lastbtn">提交</button>
            </form>
        </div>
    </main>
</body>
</html>
{% include 'footer.html' %}

BACK/VAB/templates/report/bookreport.html
{% load static %}
{% include 'topbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>举报</title>
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
    <link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/topbar_style.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/reportpage.css' %}">
    <style type="text/css">
        .wechat:hover .qrcode {
            width: 120px;
            height: auto;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(255, 99, 71, 0.5);
        }

        .qrcode {
            width: 0px;
        }

        .wechat:hover .wechat-img {
            padding-left: 40px;
        }
    </style>
    <script>
        window.onload = function () {
            var inp=document.getElementById("reason");
            var btn=document.getElementById("lastbtn");
            btn.onclick = function () {
                if (inp.value.length<15) {
                    alert("字数最少15个字！");
                }
                else
                    alert("提交成功！");
            };
        };
    </script>
</head>
<body>
    <header>
        <div class="topbook-wrap">
            <div class="bookimg iconfont">&#xe711; </div>
            <div class="bookicnline"></div>
            <div class="zi">VAB举报</div>

            <div class="find-wrap">
                <a href="{% url 'report:allMyreport' %}" class="jubaonotea">
                    <div class="jubaonote">我的举报记录</div>
                </a>
            </div>
        </div>
    </header>
    <main>
        <div class="jubaocontaincon" style="margin-top: 10px;height: 300px;">
            <div class="jubaocontain1" style="height: 20px;">
                举报地址：<a href="{% url 'Videodetail' comment.book.id %}" style="margin-top: -60px;margin-left: 100px">{{ comment.book.Book_name }}的评论</a>
            </div>
            <div class="jubaocontain2">
                您要举报的评论为：
                <div style="margin-left: 10px;border: 1px solid red;height: auto;width: auto;border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;border-top-left-radius: 10px;border-top-right-radius: 10px">
                    <div style="margin-left: 20px">{{ comment.body|safe|slice:100 }}...</div>
                </div>
                评论者：<a href="{% url 'Userprofile:profile' comment.user.id %}" style="margin-top: -60px;margin-left: 70px;height: 10px;width: 10px;color: #ff998c;font-family:JetBrains Mono">{{ comment.user.username }}</a><br>
                评论时间：<font face="Jetbrains Mono" color="#ff6347">{{ comment.created }}</font>
            </div>
        </div>
        <hr>
        <div class="jubaodiscrcon" >
            <form method="post">
                {% csrf_token %}
                <div class="jubaodiscr">问题描述</div>
                <div class="jubaodiscrinp">
                    <input type="text" class="form-control" placeholder="请输入举报理由" id="reason" name="reason">
                </div>
                <div class="jubaodiscrinp1">
                    输入你的邮箱 <input type="email" class="form-control" id="exampleInputEmail1" placeholder="{{ user.email }}" style="font-family: JetBrains Mono">
                </div>
                <div class="jubaodiscrinp1">
                    输入你的电话 <input type="text" class="form-control" placeholder="联系电话">
                </div>
                <button type="submit" class="btn btn-outline-danger" id="lastbtn">提交</button>
            </form>
        </div>
    </main>
</body>
</html>
{% include 'footer.html' %}

BACK/VAB/templates/report/handlereport.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>需处理的举报</title>
    <link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
    <link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/reportMaster.css' %}">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
</head>
{% include 'topbar.html' %}
<body>
    {% for areport in allBookReport %}
        <div class="jubaocon">
            <div class="jubaoplace">
                举报发起人
                <a href="{% url 'Userprofile:profile'  areport.reporter.id %}">
                    {{ areport.reporter.username }}
                </a>
            </div>

            <div class="jubaocontaincon">
                <div class="jubaocontain">举报内容</div>
                <div class="jubaocontain1" style="margin-left: -100px">
                    {{ areport.bookcomment.body|safe }}
                </div>
            </div>

            <div class="jubaotime">
                发表时间<span>{{ areport.bookcomment.created }}</span>
            </div>

            <div class="jubaoreasoncon">
                <div class="jubaoreason">举报原因</div>
                <div class="jubaoreason1">{{ areport.reason }}</div>
            </div>

            <div class="jubaotime1">
                举报时间<span>{{ areport.created }}</span>
            </div>
            {% if areport.state == 0 %}
                <a href="{% url 'report:refuseBR' areport.id %}" class="btn1">
                    <button type="button" class="btn btn-outline-danger">驳回</button>
                </a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'report:handleBR' areport.id %}" class="btn2">
                    <button type="button" class="btn btn-outline-success">处理</button>
                </a>
            {% elif areport.state == 1 %}
                <a href="" class="btn1" style="margin-left: 400px">
                    <button type="button" class="btn btn-outline-danger" style="width: 100px">已被驳回</button>
                </a>
            {% elif areport.state == 2 %}
                <a href="" class="btn1" style="margin-left: 400px">
                    <button type="button" class="btn btn-outline-success" style="width: 100px">已被处理</button>
                </a>
            {% endif %}
        </div>
        <div class="jubaoline"></div>
    {% endfor %}

    {% for areport in allVideoReport %}
        <div class="jubaocon">
            <div class="jubaoplace">
                举报发起人
                <a href="{% url 'Userprofile:profile'  areport.reporter.id %}">
                    {{ areport.reporter.username }}
                </a>
            </div>

            <div class="jubaocontaincon">
                <div class="jubaocontain">举报内容</div>
                <div class="jubaocontain1" style="margin-left: -100px">
                    {{ areport.videocomment.body|safe }}
                </div>
            </div>

            <div class="jubaotime">
                发表时间<span>{{ areport.videocomment.created }}</span>
            </div>

            <div class="jubaoreasoncon">
                <div class="jubaoreason">举报原因</div>
                <div class="jubaoreason1">{{ areport.reason }}</div>
            </div>

            <div class="jubaotime1">
                举报时间<span>{{ areport.created }}</span>
            </div>
            {% if areport.state == 0 %}
                <a href="{% url 'report:refuseVR' areport.id %}" class="btn1">
                    <button type="button" class="btn btn-outline-danger">驳回</button>
                </a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'report:handleVR' areport.id %}" class="btn2">
                    <button type="button" class="btn btn-outline-success">处理</button>
                </a>
            {% elif areport.state == 1 %}
                <a href="" class="btn1" style="margin-left: 400px">
                    <button type="button" class="btn btn-outline-danger" style="width: 100px">已被驳回</button>
                </a>
            {% elif areport.state == 2 %}
                <a href="" class="btn1" style="margin-left: 400px">
                    <button type="button" class="btn btn-outline-success" style="width: 100px">已被处理</button>
                </a>
            {% endif %}
        </div>
        <div class="jubaoline"></div>
    {% endfor %}

    {% for areport in allArticleReport %}
        <div class="jubaocon">
            <div class="jubaoplace">
                举报发起人
                <a href="{% url 'Userprofile:profile'  areport.reporter.id %}">
                    {{ areport.reporter.username }}
                </a>
            </div>

            <div class="jubaocontaincon">
                <div class="jubaocontain">举报内容</div>
                <div class="jubaocontain1" style="margin-left: -100px">
                    {{ areport.articlecomment.body|safe|slice:30 }}
                </div>
            </div>

            <div class="jubaotime">
                发表时间<span>{{ areport.articlecomment.created }}</span>
            </div>

            <div class="jubaoreasoncon">
                <div class="jubaoreason">举报原因</div>
                <div class="jubaoreason1">{{ areport.reason }}</div>
            </div>

            <div class="jubaotime1">
                举报时间<span>{{ areport.created }}</span>
            </div>
            {% if areport.state == 0 %}
                <a href="{% url 'report:refuseAR' areport.id %}" class="btn1">
                    <button type="button" class="btn btn-outline-danger">驳回</button>
                </a>
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                <a href="{% url 'report:handleAR' areport.id %}" class="btn2">
                    <button type="button" class="btn btn-outline-success">处理</button>
                </a>
            {% elif areport.state == 1 %}
                <a href="" class="btn1" style="margin-left: 400px">
                    <button type="button" class="btn btn-outline-danger" style="width: 100px">已被驳回</button>
                </a>
            {% elif areport.state == 2 %}
                <a href="" class="btn1" style="margin-left: 400px">
                    <button type="button" class="btn btn-outline-success" style="width: 100px">已被处理</button>
                </a>
            {% endif %}
        </div>
    {% endfor %}
</body>
</html>
<div style="width: 100%;height: 300px;"></div>
{% include 'footer.html' %}

BACK/VAB/templates/report/videoreport.html
{% load static %}
{% include 'topbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>举报</title>
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
    <link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/topbar_style.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/reportpage.css' %}">
    <style type="text/css">
        .wechat:hover .qrcode {
            width: 120px;
            height: auto;
            border-radius: 10px;
            box-shadow: 0 0 15px rgba(255, 99, 71, 0.5);
        }

        .qrcode {
            width: 0px;
        }

        .wechat:hover .wechat-img {
            padding-left: 40px;
        }
    </style>
    <script>
        window.onload = function () {
            var inp=document.getElementById("reason");
            var btn=document.getElementById("lastbtn");
            btn.onclick = function () {
                if (inp.value.length<15) {
                    alert("字数最少15个字！");
                }
                else
                    alert("提交成功！");
            };
        };
    </script>
</head>
<body>
    <header>
        <div class="topbook-wrap">
            <div class="bookimg iconfont">&#xe711; </div>
            <div class="bookicnline"></div>
            <div class="zi">VAB举报</div>

            <div class="find-wrap">
                <a href="{% url 'report:allMyreport' %}" class="jubaonotea">
                    <div class="jubaonote">我的举报记录</div>
                </a>
            </div>
        </div>
    </header>
    <main>
        <div class="jubaocontaincon" style="margin-top: 10px;height: 300px;">
            <div class="jubaocontain1" style="height: 20px;">
                举报地址：<a href="{% url 'Videodetail' comment.video.id %}" style="margin-top: -60px;margin-left: 100px">{{ comment.video.Video_name }}的评论</a>
            </div>
            <div class="jubaocontain2">
                您要举报的评论为：
                <div style="margin-left: 10px;border: 1px solid red;height: auto;width: auto;border-bottom-left-radius: 10px;border-bottom-right-radius: 10px;border-top-left-radius: 10px;border-top-right-radius: 10px">
                    <div style="margin-left: 20px">{{ comment.body|safe }}</div>
                </div>
                评论者：<a href="{% url 'Userprofile:profile' comment.user.id %}" style="margin-top: -60px;margin-left: 70px;height: 10px;width: 10px;color: #ff998c;font-family:JetBrains Mono">{{ comment.user.username }}</a><br>
                评论时间：<font face="Jetbrains Mono" color="#ff6347">{{ comment.created }}</font>
            </div>
        </div>
        <hr>
        <div class="jubaodiscrcon" >
            <form method="post">
                {% csrf_token %}
                <div class="jubaodiscr">问题描述</div>
                <div class="jubaodiscrinp">
                    <input type="text" class="form-control" placeholder="请输入举报理由" id="reason" name="reason">
                </div>
                <div class="jubaodiscrinp1">
                    输入你的邮箱 <input type="email" class="form-control" id="exampleInputEmail1" placeholder="{{ user.email }}" style="font-family: JetBrains Mono">
                </div>
                <div class="jubaodiscrinp1">
                    输入你的电话 <input type="text" class="form-control" placeholder="联系电话">
                </div>
                <button type="submit" class="btn btn-outline-danger" id="lastbtn">提交</button>
            </form>
        </div>
    </main>
</body>
</html>
{% include 'footer.html' %}