BACK/VAB/Usergroup/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from Usergroup import views

app_name = 'Usergroup'

urlpatterns = [
    path('', views.showGroup, name='showGroup'),
    path('<int:id>',views.GroupDetail, name='Groupdetail'),
    path('create',views.GroupCreate.as_view(), name='GroupCreate'),
    path('mygroup',views.MyGroupList,name='MyGroups'),
    path('join/<int:id>',views.JoinGroup,name='JoinGroup'),
    path('exit/<int:id>',views.ExitGroup,name='ExitGroup'),
    path('agreeAsk/<int:id>/',views.AgreeAsk,name='AgreeAsk'),
    path('refuseAsk/<int:id>/',views.RefuseAsk,name='RefuseAsk'),
    path('topArticle/<int:id>/<int:article_id>',views.topArticle,name='topArtilce'),
]

BACK/VAB/Userprofile/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from Userprofile import views

app_name = 'Userprofile'

urlpatterns = [
    path('', views.loadHomepage, name='loadHomepage'),
    path('register/', views.register, name='register'),
    path('login/', views.userlogin, name='login'),
    path('Userprofile/<int:id>/profile/', views.profile, name='profile'),
    path('Userprofile/<int:id>/profile/update/', views.profile_update, name='profile_update'),
    path('Userprofile/<int:id>/pwd_change/', views.pwd_change, name='pwd_change'),
    path('logout/', views.userlogout, name='logout'),
    path('registerajax/',views.registerajax,name='registerajax'),
    path('checkusers/',views.checkusers,name='checkusers'),
    path('checkusers_login/',views.checkusers_login,name='checkusers_login'),
    path('checkemail/',views.checkemail,name='checkemail'),
    path('checkpwd/',views.checkpwd,name='checkpwd'),
    path('checkpwd_login/', views.checkpwd_login, name='checkpwd_login'),
]

BACK/VAB/VAB/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
import notifications.urls

urlpatterns = [
    # 用户管理
    path('admin/', admin.site.urls),

    # 图书管理
    path('book/', include('Books.urls')),

    # 视频管理
    path('video/',include('Videos.urls')),
    
    # 用户个人信息
    path('',include('Userprofile.urls')),

    # 评论管理
    path('comment/',include('comment.urls')),

    # 帖子管理
    path('article/',include('article.urls')),

    # 通知信息
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),

    path('notice/',include('notice.urls',namespace='notice')),

    # 小组信息
    path('group/',include('Usergroup.urls',namespace='group')),

    # 举报
    path('report/',include('report.urls',namespace='report')),

    # 申请
    path('ask/',include('askManage.urls',namespace='ask')),

    # 话题
    path('topic/',include('topic.urls',namespace='topic')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BACK/VAB/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

BACK/VAB/Userprofile/models.py
from django.db import models
from django.contrib.auth.models import User


class UserProfile(models.Model):
    # CASCADE级联删除
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    org = models.CharField('Organization', max_length=255, blank=True)
    telephone = models.CharField('Telephone', max_length=50, blank=True)
    mod_date = models.DateTimeField('last modified', auto_now=True)
    headshot = models.ImageField(upload_to='headshot/', null=True)
    personal_infor = models.TextField(max_length=500, blank=True)
    # birthday = models.DateTimeField(blank=True,null=True)

    class Meta:
        verbose_name = 'User profile'

    def __str__(self):
        return "{}".format(self.user.__str__)


'''
User模型自带属性：
    username：用户名
    email: 电子邮件
    password：密码
    first_name：名
    last_name：姓
    is_active: 是否为活跃用户。默认是True
    is_staff: 是否为员工。默认是False
    is_superuser: 是否为管理员。默认是False
    date_joined: 加入日期。系统自动生成
'''

BACK/VAB/Userprofile/forms.py
from django import forms
from django.contrib.auth.models import User
import re  # 正则模块


def email_check(email):
    pattern = re.compile(r"\"?([-a-zA-Z0-9.'?{}]+@\w+\.\w+)\"?")
    return re.match(pattern, email)


# 注册表类
class RegistrationForm(forms.Form):
    username = forms.CharField(label='Username', max_length=255)
    email = forms.EmailField(label='Email')
    password_1 = forms.CharField(label='Password', widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

    # 清洗验证用户名
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if len(username) < 3:
            raise forms.ValidationError("用户名必须大于三个字段")
        elif len(username) > 50:
            raise forms.ValidationError("用户名必须小于50个字段")
        else:
            filter_result = User.objects.filter(username__exact=username)
            if len(filter_result) > 0:
                raise forms.ValidationError("该用户名已存在")

        return username

    # 清洗验证邮箱
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email_check(email):
            filter_result = User.objects.filter(email__exact=email)
            if len(filter_result) > 0:
                raise forms.ValidationError("该邮箱已经存在")
        else:
            raise forms.ValidationError("请输入有效邮件地址")

        return email

    # 清洗验证密码
    def clean_password_1(self):
        password_1 = self.cleaned_data.get('password_1')
        if len(password_1) < 3:
            raise forms.ValidationError("密码太短")
        elif len(password_1) > 20:
            raise forms.ValidationError("密码太长")

        return password_1

    def clean_password_2(self):
        password_1 = self.cleaned_data.get('password_1')
        password_2 = self.cleaned_data.get('password_2')

        if password_1 and password_2 and password_1 != password_2:
            raise forms.ValidationError('两次密码输入不同')

        return password_2


# 登录类
class LoginForm(forms.Form):
    username = forms.CharField(label='Username', max_length=50)
    password = forms.CharField(label='Password', widget=forms.PasswordInput)

    # 清洗验证用户名
    def clean_username(self):
        username = self.cleaned_data.get('username')
        if email_check(username):
            filter_result = User.objects.filter(email__exact=username)
            if not filter_result:
                raise forms.ValidationError('该邮箱不存在')
        else:
            filter_result = User.objects.filter(username__exact=username)
            if not filter_result:
                raise forms.ValidationError('该用户名不存在，请先注册')

        return username


# 用户信息
class ProfileForm(forms.Form):
    first_name = forms.CharField(label='First Name', max_length=50, required=False)
    last_name = forms.CharField(label='Last Name', max_length=50, required=False)
    org = forms.CharField(label='Organization', max_length=50, required=False)
    telephone = forms.CharField(label='Telephone', max_length=50, required=False)
    personal_infor = forms.CharField(label='Personal_intro',required=False)


# 修改密码
class PwdChangeForm(forms.Form):
    old_password = forms.CharField(label='Old Password', widget=forms.PasswordInput)
    password_1 = forms.CharField(label='New Password', widget=forms.PasswordInput)
    password_2 = forms.CharField(label='Password Confirmation', widget=forms.PasswordInput)

    def clean_password_1(self):
        password_1 = self.cleaned_data.get('password_1')

        if len(password_1) < 6:
            raise forms.ValidationError("密码太短了")
        elif len(password_1) > 20:
            raise forms.ValidationError("密码太长了")

        return password_1

    def clean_password_2(self):
        password_1 = self.cleaned_data.get('password_1')
        password_2 = self.cleaned_data.get('password_2')

        if password_1 and password_2 and password_1 != password_2:
            raise forms.ValidationError("两次密码不匹配，请重新输入")

        return password_2

BACK/VAB/Userprofile/views.py
from django.shortcuts import render, HttpResponse, get_object_or_404, redirect
from .forms import RegistrationForm, LoginForm, ProfileForm, PwdChangeForm
from .models import UserProfile
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.contrib import messages
from django.http import HttpResponseRedirect,JsonResponse
from django.contrib import auth,messages
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from article.models import Article
from Books.models import Book
from Videos.models import Video

# VAB主站点
def loadHomepage(request):
    articles = []
    books = []
    videos = []

    acount = 3
    bcount = 3
    vcount = 3

    if Article.objects.all().count() < 3:acount = Article.objects.all().count()
    if Book.objects.all().count() < 3:bcount = Book.objects.all().count()
    if Video.objects.all().count() < 3:vcount = Video.objects.all().count()

    alist = Article.objects.all().order_by('-total_views')
    blist = Book.objects.all().order_by('-Book_total_views')
    vlist = Video.objects.all()

    for i in range(0,acount):articles.append(alist[i])
    for j in range(0,bcount):books.append(blist[j])
    for k in range(0,vcount):videos.append(vlist[k])

    context = {'articles':articles,'books':books,'videos':videos}

    return render(request, 'homepage.html',context)

# 个人信息
@login_required
def profile(request, id):
    user = User.objects.get(id=id)
    userprofile = UserProfile.objects.get(user_id=id)
    return render(request, 'Userprofile/profile.html', {'user': user,'userprofile':userprofile})


# 更新个人信息
@login_required
def profile_update(request, id):
    user = get_object_or_404(User, pk=id)
    user_profile = get_object_or_404(UserProfile, user=user)

    if request.method == 'POST':
        if request.user != user:
            return HttpResponse("你没有权限修改该用户的个人信息")

        form = ProfileForm(request.POST,request.FILES)

        if form.is_valid():
            # 从表单中洗出数
            user.first_name = form.cleaned_data['first_name']
            user.last_name = form.cleaned_data['last_name']
            user.save()

            user_profile.telephone = form.cleaned_data['telephone']
            user_profile.personal_infor = form.cleaned_data['personal_infor']
            # user_profile.birthday = form.cleaned_data['date1']

            if 'file_profile' in request.FILES:
                user_profile.headshot = request.FILES.get('file_profile')

            user_profile.save()
            return redirect("Userprofile:profile",id=user.id)
        else:
            return HttpResponse("个人信息更新错误，请重试")

    else:
        default_data = {'user':user,
                        'first_name': user.first_name,
                        'last_name': user.last_name,
                        'org': user_profile.org,
                        'userprofile':user_profile,
                        'telephone': user_profile.telephone,
                        'personal_intro':user_profile.personal_infor,
                        'headshot':user_profile.headshot,
                        'email':user.email,}
        form = ProfileForm()

    return render(request, 'Userprofile/profile_update.html', default_data)


# 注册
def register(request):
    if request.method == 'POST':
        form = RegistrationForm(request.POST)

        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            orgin_pwd = form.cleaned_data['password_1']
            password = form.cleaned_data['password_2']

            # 使用内置create
            user = User.objects.create_user(username=username,
                                            password=password,
                                            email=email)
            userprofile = UserProfile.objects.create(user=user)
            login(request,user)
            return redirect('showBook')
        else:
            return HttpResponse("<script>alert('填写错误，请重试');location.href=\"\";</script>")

    else:
        form = RegistrationForm()
        return render(request, 'Userprofile/registration.html', {'form': form})


# 登录
def userlogin(request):
    if request.method == 'POST':
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            print(username)
            print(password)

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                auth.login(request, user)
                print(user.id)
                # return redirect('Userprofile:profile', id=user.id)
                return redirect('showBook')
            else:
                return render(request, 'Userprofile/login.html', {'form': form,
                                                                  'message': '用户名或密码错误，请再输一次'})

    else:
        form = LoginForm()

    return render(request, 'Userprofile/login.html', {'form': form})


# 登出
@login_required
def userlogout(request):
    logout(request)
    return redirect('Userprofile:loadHomepage')


# 修改密码
@login_required
def pwd_change(request, pk):
    user = get_object_or_404(User, pk=pk)

    if request.method == 'POST':
        form = PwdChangeForm(request.POST)

        if form.is_valid():
            password = form.cleaned_data['old_password']
            username = user.username

            user = auth.authenticate(username=username, password=password)

            if user is not None and user.is_active:
                new_password = form.cleaned_data['password_2']
                user.set_password(new_password)
                user.save()
                return HttpResponseRedirect('/accounts/login/')
            else:
                return render(request, 'Userprofile/pwd_change.html',
                              {'form': form, 'user': user, 'message': '您的旧密码不对，请重新输入'})

    else:
        form = PwdChangeForm()

    return render(request, 'Userprofile/pwd_change.html', {'form': form, 'user': user})

# 处理ajax请求
def registerajax(request):
    result = {"code":1000,"msg":""}

    if request.method == "POST":
        username = request.POST.get("username")
        password_1 = request.POST.get("password_1")
        password_2 = request.POST.get("password_2")
        email = request.POST.get("email")

        if username and password_1 and password_2:
            user = User.objects.filter(username__exact=username).first()
            emailueser = User.objects.filter(email__exact=email).first()
            if user:
                result = {"code":1001,"msg":"用户名已被使用"}
            else:
                if emailueser:
                    result = {"code": 1002, "msg": "邮箱已被使用"}
                else:
                    if password_1 != password_2:
                        result = {"code": 1003, "msg": "两次输入的密码不一样"}
                    else:
                        newuser = User.objects.create_user(username=username,
                                                        password=password_2,
                                                        email=email)
                        userprofile = UserProfile.objects.create(user=newuser)
                        result = {"code":1004,"msg":"注册成功"}
        else:
            result = {"code": 1005, "msg": "用户名或者密码为空"}
    return JsonResponse(result)


# 判断用户是否存在
def checkusers(request):
    result = {"code":2000,"msg":""}
    username = request.GET.get("username")
    if username:
        user = User.objects.filter(username__exact=username).first()
        if user:
            result = {"code":2000,"msg":"用户名存在"}
        else:
            result = {"code": 2001, "msg": ""}
    else:
        result = {"code": 2002, "msg": "请输入用户名"}
    return JsonResponse(result)

# 判断用户是否存在
def checkusers_login(request):
    result = {"code":2000,"msg":""}
    username = request.GET.get("username")
    if username:
        user = User.objects.filter(username__exact=username).first()
        if user:
            result = {"code":2000,"msg":""}
        else:
            result = {"code": 2001, "msg": "用户名不存在"}
    else:
        result = {"code": 2002, "msg": "请输入用户名"}
    return JsonResponse(result)


# 判断邮箱是否已经被使用
def checkemail(request):
    result = {"code":3000,"msg":""}
    email = request.GET.get("email")
    if email:
        user = User.objects.filter(email__exact=email).first()
        if user:
            result = {"code":3000,"msg":"邮箱已被使用"}
        else:
            result = {"code": 3001, "msg": ""}
    else:
        result = {"code": 3002, "msg": "请输入邮箱"}
    return JsonResponse(result)

# 密码是否重复
def checkpwd(request):
    result = {"code": 4000, "msg": ""}

    pwd_1 = request.GET.get("password_1")
    pwd_2 = request.GET.get("password_2")


    if pwd_1 and pwd_2:
        if pwd_1 != pwd_2:
            result = {"code": 4000, "msg": "密码不一致"}
        else:
            result = {"code": 4001, "msg": ""}
    else:
        result = {"code": 4002, "msg": "请输入密码"}
    return JsonResponse(result)

def checkpwd_login(request):
    result = {"code": 4000, "msg": ""}
    username = request.GET.get("username")
    password = request.GET.get("password")

    print(username)
    print(password)

    if username and password:
        user = User.objects.filter(username__exact=username,password=password).first()
        if user:
            result = {"code": 4000, "msg": ""}
        else:
            result = {"code": 4001, "msg": ""}
    else:
        result = {"code": 4002, "msg": "请输入用户名和密码"}
    return JsonResponse(result)

BACK/VAB/templates/Userprofile/findpwd.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

BACK/VAB/templates/Userprofile/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>登录</title>
    <link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
    <link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
    <!-- 引入公用样式 -->
    <link rel="stylesheet" href="{% static '/css_style/base.css' %}">
    <!-- 引入本页面的样式 -->
    <link rel="stylesheet" href="{% static '/css_style/index.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
</head>
<body>
<link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
<link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
<!-- 引入公用样式 -->
<link rel="stylesheet" href="{% static '/css_style/base.css' %}">
<!-- 引入本页面的样式 -->
<link rel="stylesheet" href="{% static '/css_style/index.css' %}">
    <header>
        <ul class="topbar">
            <li class="logo-wrap">
                <img src="{% static '/vab_img/logo.jpg.png' %}" alt="logo" class="logo">
            </li>
            <li class="line-wrap">
                <div class="line"></div>
            </li>
            <li class="home">
                <a href="{% url 'Userprofile:loadHomepage' %}" class="iconfont">&#xe61f;
                    <p>home</p>
                </a>
            </li>
            <li class="book">
                <a href="{% url 'showBook' %}" class="iconfont">&#xe66c;
                    <p>book</p>
                </a>
            </li>
            <li class="video">
                <a href="{% url 'showVideo' %}" class="iconfont">&#xe605;
                    <p>video</p>
                </a>
            </li>
            <li class="group">
                <a href="{% url 'group:showGroup' %}" class="iconfont">
                    &#xe654;
                    <p>group</p>
                </a>
            </li>
            <li class="topic">
                <a href="{% url 'showArticle' %}" class="iconfont">
                    &#xe8b1;
                    <p>topic</p>
                </a>
            </li>
            <li class="user-wrap">
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            {% if unread_count %}
                                <svg viewBox="0 0 8 8" width="8px" height="8px">
                                    <circle cx="4" cy="4" r="4" fill="#ff6b6b"></circle>
                                </svg>
                            {% endif %}
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <a class="dropdown-item" href="{% url "notice:list" %}">通知
                                {% if unread_count %}
                                    <span class="badge badge-danger">{{ unread_count }}</span>
                                {% endif %}
                            </a>
                            <a class="dropdown-item" href="{% url 'ArticleCreate' %}">写文章</a>
                            <a class="dropdown-item" href='{% url "Userprofile:profile" user.id %}'>个人信息</a>
                            <a class="dropdown-item" href='{% url "Userprofile:logout" %}'>退出登录</a>
                        </div>
                    </li>


                {% else %}
                <a href="{% url 'Userprofile:login' %}" class="user1">
                    登录
                </a>
                <i class="iconfont l">&#xe63a;</i>
                <a href="{% url 'Userprofile:register' %}" class="user1">
                    注册
                </a>
                {% endif %}
            </li>
        </ul>
    </header>

<script>
    {% if message %}
        alert('{{ message }}')
    {% endif %}
</script>

    <main>
        <div class="geometric-container">
            <div class="box1">
                <img src="{% static '/vab_img/1.png' %}" alt="">
            </div>
            <div class="box2">
                <img src="{% static '/vab_img/2.png' %}" alt="">
            </div>
            <div class="box3">
                <img src="{% static '/vab_img/3.png' %}" alt="">
            </div>
            <div class="box4">
                <img src="{% static '/vab_img/4.png' %}" alt="">
            </div>
            <div class="box5">
                <img src="{% static '/vab_img/5.png' %}" alt="">
            </div>
            <div class="box6">
                <img src="{% static '/vab_img/6.png' %}" alt="">
            </div>
        </div>
        <div class="longline"></div>
        <div class="form-container">
            <a href="{% url 'Userprofile:loadHomepage' %}" class="iconfont jump">直接跳过&#xe60d;</a>
            <form action="" class="form-inp" method="post">
                {% csrf_token %}
                <div style="height: 100px;">
                    <label for="username"><font face="kaiti">用户名</font></label>
                    <input type="text" class="username" placeholder="  Username" id="username" name="username">
                    <span id="msgname" style="color: #ff7d79;margin-left:100px;font-size: small"></span>
                </div>
                <div style="height: 80px;">
                    <label for="password"><font face="kaiti">密码&nbsp;&nbsp;</font></label>
                    <input type="password" class="password" placeholder="  Password" id="password" name="password">
                    <span id="msgpassword" style="color: #ff7d79;margin-left:100px;font-size: small"></span>
                </div>
                <button class="login-btn">登录</button>
            </form>
            <div class="ornot-wrap">
                <input type="checkbox" name="ornot" value="ornot" class="ornot">
                自动登录
                <div class="forget">忘记密码？
                    <a href="#">注册</a>
                </div>
            </div>
        </div>
    </main>
    {% include 'footer.html' %}
</body>
</html>

<script>
        $("#username").blur(
        function () {
            var username = $("#username").val();
            var url = "/checkusers_login/?username=" + username;
            $.ajax({
                url:url,
                type: "get",
                data: "",

                success:function (data) {
                    console.log(data);
                    $("#msgname").text(data["msg"]);
                },
                error:function () {
                    // others
                }
            })
        }
    )

        $("#password").blur(
        function () {
            var username = $("#username").val()
            var password = $("#password").val()

            var url = "/checkpwd_login/?username=" + username + "&password=" + password;

            $.ajax({
                url:url,
                type:"get",
                data:"",

                success:function (data) {
                    console.log(data);
                    $("#msgpassword").text(data["msg"]);
                },
                error:function () {
                    // others
                }
            })
        }
    )
</script>

BACK/VAB/templates/Userprofile/profile.html
{% load static %}
{% include 'topbar.html' %}
<!doctype html>
<html ng-app="app" lang="en">
<head>
	<meta charset="utf-8">
	<title>{{ user.username }}的个人主页</title>
	<link rel="stylesheet" href="{% static '/css_style/base.css' %}">
	<link rel="stylesheet" href="{% static '/css_style/personal_information.css' %}">

	<link rel="stylesheet" type="text/css" href="{% static '/css_style/birthday/wui.min.css' %}">

	<link rel="stylesheet" href="{% static '/css_style/limit/normalize.min.css' %}">
    <link rel="stylesheet prefetch" href="{% static '/css_style/limit/animate.min.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/limit/style.css' %}">


	<script type="text/javascript" src="{% static '/js/personal_information/date/jquery.min.js' %}"></script>
	<script type="text/javascript" src="{% static '/js/personal_information/date/angular.min.js' %}"></script>
	<script type="text/javascript" src="{% static '/js/personal_information/date/wui-date.js' %}" charset="utf-8"></script>
	<script type="text/javascript">var app = angular.module('app',["wui.date"]);</script>
  	<script type="text/javascript">
		function previewFile() {
		 var preview = document.querySelector('.img-pro');
		 var file  = document.querySelector('input[type=file]').files[0];
		 var reader = new FileReader();
		 reader.onloadend = function () {
		  preview.src = reader.result;
		 }
		 if (file) {
		  reader.readAsDataURL(file);
		 } else {
		  preview.src = "img-p";
		 }
		}
	</script>
</head>

<body>
	<div class="personal_page" id="personal_page" style="margin-top: 100px">
		<form>
			<div class="person_head">
				<div class="profile_picture" >
                    {% if userprofile.headshot %}
                        <img src="{{ userprofile.headshot.url }}" class="img-pro" alt="">
                    {% else %}
                        <div style="width: 145px;height: 140px;border: 3px dashed #ffb0a4;border-top-right-radius: 10px;border-top-left-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 10px;background: #d3cfd6">
                            <div style="margin-top: 60px;margin-left: 38px">
                                暂无头像
                            </div>
                        </div>
                    {% endif %}
				</div>
				<div class="words">
					<input type="text" class="head_username" placeholder="{{ user.username }}" readonly><br/>
					<input type="text" class="sentence" placeholder="{{ userprofile.personal_infor }}" readonly>

                    <a href="{% url 'Userprofile:profile_update' user.id %}" style="margin-left: 85%">
                        <button class="btn btn-outline-danger" type="button">
                            修改资料
                        </button>
                    </a>
				</div>
			</div>
			<div id="tree">
				<script src="{% static '/js/personal_information/tree/person_tree_script.js' %}"></script>
			</div>
			<div class="person_information" style="height: 500px;">
                <div style="width: 600px;margin-left:40px;border: 2px dashed #ffb0a4;border-top-right-radius: 10px;border-top-left-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 10px;background: #fff0eb">
                    &nbsp;&nbsp;用&nbsp;户&nbsp;&nbsp;名：<input type="text" class="username" placeholder="{{ user.username }}" readonly><br/>
                    &nbsp;&nbsp;姓&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;：<input type="text" class="username" placeholder="{{ user.first_name }}" readonly><br/>
                    &nbsp;&nbsp;名&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;：<input type="text" class="username" placeholder="{{ user.last_name }}" readonly><br/>
{#                    生&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;日：<wui-date format="yyyy-mm-dd" placeholder="请选择或输入日期" id="date1" btns="{'ok':'确定','now':'此刻'}" ng-model="date1"></wui-date><br/>#}
                    &nbsp;&nbsp;电&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;话：<input type="tel" placeholder="{{ userprofile.telephone }}" class="tel" readonly><br/>
                    &nbsp;&nbsp;邮&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;箱：<input type="email" placeholder="{{ user.email }}" class="email" readonly><br/><br/>
                </div>

{#				简&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;介：<div id="root" style="margin-left: 100px"></div>#}
				<script type="text/javascript"  src="{% static '/js/personal_information/limit/react.min.js' %}"></script>
				<script type="text/javascript"  src="{% static '/js/personal_information/limit/react-dom.min.js' %}"></script>
				<script type="text/javascript"  src="{% static '/js/personal_information/limit/prop-types.js' %}"></script>
				<script type="text/javascript"   src="{% static '/js/personal_information/limit/index.js' %}"></script>
{#				<div class="submit">#}
{#					<button>确认修改</button>#}
{#					<button>取消</button>#}
{#				</div>#}
			</div>
		</form>
	</div>
</body>
</html>
{% include 'footer.html' %}

BACK/VAB/templates/Userprofile/pwd_change.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>password Change</title>
</head>
<body>

</body>
</html>