BACK/VAB/Usergroup/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from Usergroup import views

app_name = 'Usergroup'

urlpatterns = [
    path('', views.showGroup, name='showGroup'),
    path('<int:id>',views.GroupDetail, name='Groupdetail'),
    path('create',views.GroupCreate.as_view(), name='GroupCreate'),
    path('mygroup',views.MyGroupList,name='MyGroups'),
    path('join/<int:id>',views.JoinGroup,name='JoinGroup'),
    path('exit/<int:id>',views.ExitGroup,name='ExitGroup'),
    path('agreeAsk/<int:id>/',views.AgreeAsk,name='AgreeAsk'),
    path('refuseAsk/<int:id>/',views.RefuseAsk,name='RefuseAsk'),
    path('topArticle/<int:id>/<int:article_id>',views.topArticle,name='topArtilce'),
]

BACK/VAB/VAB/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
import notifications.urls

urlpatterns = [
    # 用户管理
    path('admin/', admin.site.urls),

    # 图书管理
    path('book/', include('Books.urls')),

    # 视频管理
    path('video/',include('Videos.urls')),
    
    # 用户个人信息
    path('',include('Userprofile.urls')),

    # 评论管理
    path('comment/',include('comment.urls')),

    # 帖子管理
    path('article/',include('article.urls')),

    # 通知信息
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),

    path('notice/',include('notice.urls',namespace='notice')),

    # 小组信息
    path('group/',include('Usergroup.urls',namespace='group')),

    # 举报
    path('report/',include('report.urls',namespace='report')),

    # 申请
    path('ask/',include('askManage.urls',namespace='ask')),

    # 话题
    path('topic/',include('topic.urls',namespace='topic')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BACK/VAB/notice/urls.py
from django.urls import path
from . import views

app_name = 'notice'

urlpatterns = [
    # 通知列表
    path('list/', views.CommentNoticeListView.as_view(), name='list'),
    # 更新通知状态
    path('update/', views.CommentNoticeUpdateView.as_view(), name='update'),
]

BACK/VAB/report/urls.py
from django.urls import path
from . import views

app_name = 'report'

urlpatterns = [
    path('report-Bookcomment/<int:id>/',views.RBookComment,name='report_Bookcomment'),
    path('report-Videocomment/<int:id>/',views.RVideoComment,name='report_Videocomment'),
    path('report-Articlecomment/<int:id>/',views.RArticleComment,name='report_Articlecomment'),
    path('allMyreport',views.LookAllMyReport,name='allMyreport'),
    path('needhandle',views.needhandleReport,name='needHandle'),
    path('refuse-bookreport/<int:id>/',views.refusebookreport,name='refuseBR'),
    path('refuse-videoreport/<int:id>/',views.refusevideoreport,name='refuseVR'),
    path('refuse-articlereport/<int:id>/',views.refusearticlereport,name='refuseAR'),
    path('handle-bookreport/<int:id>/',views.handlebookreport,name='handleBR'),
    path('handle-videoreport/<int:id>/',views.handlevideoreport,name='handleVR'),
    path('handle-articlereport/<int:id>/',views.handlearticlereport,name='handleAR'),
]

BACK/VAB/topic/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from topic import views

app_name = 'topic'

urlpatterns = [
    path('',views.alltopics,name='alltopics'),
    path('topic-create/',views.createTopic,name='CreateTopic'),
    path('topic-detail/<int:id>/',views.topicDetail,name='TopicDetail'),
]

BACK/VAB/templates/footer.html
{% load static %}
<!doctype html>
<html>
	<head>
		<meta charset="utf-8">
		<title>footer</title>
		<style type="text/css">
			.wechat:hover .qrcode{
				width: 120px;
				height: auto;
				border-radius: 10px;
				box-shadow: 0 0 15px rgba(255,99,71,0.5);
			}
			.qrcode{
				width: 0px;
			}
			.wechat:hover .wechat-img{
				padding-left: 40px;
                width: 40px;
				height: 40px;
			}
            .wechat-img{
				width: 40px;
				height: 40px;
			}
		</style>
	</head>

	<body>
	</body>

	<footer style=" background-color: rgb(243, 191, 182); color: rgb(255, 255, 255); padding: 30px 50px;font-family:Consolas, 'Andale Mono', 'Lucida Console', 'Lucida Sans Typewriter', Monaco, 'Courier New', 'monospace';height: auto">
		<div style="display: flex; flex-direction: column; align-items: center;">
			<div style="margin: 12px 0px;margin-bottom: 17px;">
				<table>
					<tr style="height: 35px;">
						<td>
							<img src="{%  static '/vab_img/logo.jpg.png' %}" alt="logo" style="width: auto; height:35px;" >
						</td>
						<td style="height: 35px;line-height: 35px;color: #FF6347;font-weight: bold">
							&nbsp;&nbsp;Vedio and book
						</td>
					</tr>
				</table>
			</div>
			<div style="margin: 8px 0px;">Copyright &copy;2020  by “VAB Group”
			</div>
			<div style="margin: 8px 0px;">若本站收录内容无意侵犯了贵公司版权，请给网页底部微信或邮箱地址来信，我们会及时处理和回复，谢谢合作</div>
			<div style="margin: 8px 0px;">Email：1730639879@qq.com</div>
			<div style="width: 300px;height: 1px; background-color: #FFFFFF;margin-top: 20px;"></div>
			<div style="margin: 8px 0px; margin-top: 13px;height: auto;">
				<a href="#" class="wechat">
					<div class="wechat-img">
						<img src={% static '/vab_img/logo_wx.png' %} alt="微信" style="width: 40px;height: 40px;">
					</div>
					<div style="border-radius: 10px; border-radius: 10px;color: rgba(255,99,71,1.00);">
						<img class="qrcode" src="https://s1.ax1x.com/2020/03/31/GlpztO.md.jpg" alt="微信二维码">
					</div>
				</a>
			</div>
		</div>
	</footer>
</html>

BACK/VAB/templates/sidebar.html
{% load static %}
<div class="book_label-wrap">
    <div class="outer">
        <div class="action">行动</div>
        <ul class="ul-container">
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'ArticleCreate' %}">
                    <img src="{% static '/vab_img/文章.png' %}" class="article" style="width: 40px;height: 40px;">
                    <div>写文章</div>
                </a>
            </li>
            <li>
                <a href="{% url 'Bookupload' %}">
                    <img src="{% static '/vab_img/书.png' %}" class="book" style="width: 40px;height: 40px;">
                    <div>推书籍</div>
                </a>
            </li>
            <li>
                <a href="{% url 'Videoupload' %}" class="movie-wrap">
                    <img src="{% static '/vab_img/电视机.png' %}" class="movie" style="width: 40px;height: 40px;">
                    <div>推影视</div>
                </a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'Usergroup:MyGroups' %}">
                    <img src="{% static '/vab_img/小组.png' %}" class="group" style="width: 40px;height: 40px;">
                    <div>查看小组</div>
                </a>
            </li>
            <li>
                <a href="{% url 'showArticle' %}">
                    <img src="{% static '/vab_img/话题.png' %}" class="topic" style="width: 40px;height: 40px;">
                    <div>话题广场</div>
                </a>
            </li>
        </ul>
    </div>
    <div class="outer1">
        <div class="iconfont label">&#xe662; 快速标签查找</div>
        <div class="line"></div>
        <ul class="ul-container">
            <li class="literature-wrap">
                <div class="literature">文学</div>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=小说">小说</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=传记">传记</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=纪实">纪实</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=影视">影视</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=诗歌">诗歌</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=童话">童话</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=期刊杂志">期刊杂志</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=戏剧">戏剧</a>
            </li>
            <li>
                <a href="{% url 'showBook' %}?order=Book_total_views&search=美术">美术</a>
            </li>
        </ul>
        <div class="line"></div>
        <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">历史</div>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=中国史">中国史</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=世界史">世界史</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=考古学">考古学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=畅销史书">畅销史书</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=民族学">民族学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=史学理论">史学理论</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">计算机</div>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=操作系统">操作系统</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=网络安全">网络安全</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=电子商务">电子商务</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=硬件开发">硬件开发</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=数据库">数据库</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=程序设计">程序设计</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=人工智能">人工智能</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=算法">算法</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=编程语言">编程语言</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">哲学</div>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=东方哲学">东方哲学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=西方哲学">西方哲学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=哲学史">哲学史</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=马克思">马克思</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=逻辑学">逻辑学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=伦理学">伦理学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=美学">美学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=宗教">宗教</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">科技</div>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=机械">机械</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=建筑">建筑</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=电子通信">电子通信</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=化学">化学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=物理">物理</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=水利">水利</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=能源与动力">能源与动力</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=生物医学">生物医学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=矿业与冶炼">矿业与冶炼</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">社会</div>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=经济">经济</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=管理">管理</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=心理">心理</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=商务实务">商务实务</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=财政税收">财政税收</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=银行与货币">银行与货币</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">考研</div>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=考研数学">考研数学</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=考研英语">考研英语</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=考研政治">考研政治</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=考研计算机">考研计算机</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">青年</div>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=玄幻">玄幻</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=言情">言情</a>
        </li>
        <li>
            <a href="{% url 'showBook' %}?order=Book_total_views&search=侦探">侦探</a>
        </li>
    </ul>
    </div>
</div>

BACK/VAB/templates/topbar.html
{% load static %}
{% load notifications_tags %}
{% notifications_unread as unread_count %}
<link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
<link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
<link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
<!-- 引入公用样式 -->
<link rel="stylesheet" href="{% static '/css_style/base.css' %}">
<!-- 引入本页面的样式 -->
<link rel="stylesheet" href="{% static '/css_style/index.css' %}">
{#<link rel="stylesheet" href="{% static '/css_style/topbar_style.css' %}">#}
<script src="{% static 'jquery/jquery-3.3.1.js' %}"></script>
<script src="{% static 'popper/popper-1.14.4.js' %}"></script>
<script src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
<header>
    <ul class="topbar">
        <li class="logo-wrap">
            <a href="{% url 'Userprofile:loadHomepage' %}">
                <img src="{% static '/vab_img/logo.jpg.png' %}" alt="logo" class="logo" style="width:auto ;height: 40px;margin-left: 20px;margin-top: 10px">
            </a>
        </li>
        <li class="line-wrap">
            <div class="line"></div>
        </li>
        <li class="home">
            <a href="{% url 'Userprofile:loadHomepage' %}" class="iconfont">
                &#xe61f;&nbsp;
                <p><font face="JetBrains Mono">home</font></p>
            </a>
        </li>
        <li class="book">
            <a href="{% url 'showBook' %}" class="iconfont">
                &#xe66c;&nbsp;&nbsp;
                <p><font face="JetBrains Mono">book</font></p>
            </a>
        </li>
        <li class="video">
            <a href="{% url 'showVideo' %}" class="iconfont">
                &#xe605;&nbsp;
                <p><font face="JetBrains Mono">video</font></p>
            </a>
        </li>
        <li class="group">
            <a href="{% url 'Usergroup:showGroup' %}" class="iconfont">
                &#xe654;&nbsp;
                <p><font face="JetBrains Mono">group</font></p>
            </a>
        </li>
        <li class="topic">
            <a href="{% url 'showArticle' %}" class="iconfont">
                &#xe8b1;&nbsp;
                <p><font face="JetBrains Mono">topic</font></p>
            </a>
        </li>

        {% if user.is_authenticated %}
            <li class="nav-item dropdown" style="margin-top: -15px">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="height: 50px;">
                    {% if unread_count %}
                        <div style="margin-left: -10px;height: 0px;width: 10px;">
                            <svg viewBox="0 0 8 8" width="8px" height="8px">
                                <circle cx="4" cy="4" r="4" fill="#ff6b6b"></circle>
                            </svg>
                        </div>
                    {% endif %}
                    <div style="width: 80px;height: 50px;font-family: 'JetBrains Mono', serif;font: bold">{{ user.username }}</div>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdown" >
                    <a class="dropdown-item" href="{% url "notice:list" %}">通知
                        {% if unread_count %}
                            <span class="badge badge-danger">{{ unread_count }}</span>
                        {% endif %}
                    </a>
                    <a class="dropdown-item" href="{% url 'ArticleCreate' %}">写文章</a>
                    <a class="dropdown-item" href="{% url 'Usergroup:MyGroups' %}">我的小组</a>
                    <a class="dropdown-item" href='{% url "Userprofile:profile" user.id %}'>个人信息</a>
                    {% if user.is_superuser %}
                        <a class="dropdown-item" href='{% url "report:needHandle" %}'>查看需要处理的举报</a>
                    {% else  %}
                        <a class="dropdown-item" href='{% url "report:allMyreport" %}'>查看我的举报</a>
                    {% endif %}
                    <a class="dropdown-item" href='{% url "ask:allMyasks" user.id%}'>我的申请记录</a>
                    <a class="dropdown-item" href='{% url "ask:NeedHandleAsks" user.id%}'>处理申请</a>
                    <a class="dropdown-item" href='{% url "topic:alltopics" %}'>话题广场</a>
                    <a class="dropdown-item" href='{% url "topic:CreateTopic" %}'>新建话题</a>
                    <a class="dropdown-item" href='{% url "Userprofile:logout" %}' style="margin-bottom:0px;background: #fff0eb;border: 2px dashed #ffdfeb;border-top-right-radius: 10px;border-top-left-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 10px;">退出登录</a>
                </div>
            </li>
        {% else %}
            <li class="user-wrap">
                <a href="{% url 'Userprofile:login' %}" class="user1" style="width: 50px;">
                    登录
                </a>
                <i class="iconfont l">&#xe63a;</i>
                <a href="{% url 'Userprofile:register' %}" class="user1" style="width: 50px;">
                    注册
                </a>
            </li>
        {% endif %}
    </ul>
</header>

BACK/VAB/templates/videosidebar.html
{% load static %}
<div class="book_label-wrap">
    <div class="outer">
        <div class="action">行动</div>
        <ul class="ul-container">
            {% if user.is_authenticated %}
            <li>
                <a href="{% url 'ArticleCreate' %}">
                    <img src="{% static '/vab_img/文章.png' %}" class="article" style="width: 40px;height: 40px;">
                    <div>写文章</div>
                </a>
            </li>
            <li>
                <a href="{% url 'Videoupload' %}">
                    <img src="{% static '/vab_img/书.png' %}" class="book" style="width: 40px;height: 40px;">
                    <div>推书籍</div>
                </a>
            </li>
            <li>
                <a href="{% url 'Videoupload' %}" class="movie-wrap">
                    <img src="{% static '/vab_img/电视机.png' %}" class="movie" style="width: 40px;height: 40px;">
                    <div>推影视</div>
                </a>
            </li>
            {% endif %}
            <li>
                <a href="{% url 'Usergroup:MyGroups' %}">
                    <img src="{% static '/vab_img/小组.png' %}" class="group" style="width: 40px;height: 40px;">
                    <div>查看小组</div>
                </a>
            </li>
            <li>
                <a href="{% url 'showArticle' %}">
                    <img src="{% static '/vab_img/话题.png' %}" class="topic" style="width: 40px;height: 40px;">
                    <div>话题广场</div>
                </a>
            </li>
        </ul>
    </div>
    <div class="outer1">
        <div class="iconfont label">&#xe662; 快速标签查找</div>
        <div class="line"></div>
        <ul class="ul-container">
            <li class="literature-wrap">
                <div class="literature">文学</div>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=小说">小说</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=传记">传记</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=纪实">纪实</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=影视">影视</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=诗歌">诗歌</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=童话">童话</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=期刊杂志">期刊杂志</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=戏剧">戏剧</a>
            </li>
            <li>
                <a href="{% url 'showVideo' %}?search=美术">美术</a>
            </li>
        </ul>
        <div class="line"></div>
        <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">历史</div>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=中国史">中国史</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=世界史">世界史</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=考古学">考古学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=畅销史书">畅销史书</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=民族学">民族学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=史学理论">史学理论</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">计算机</div>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=操作系统">操作系统</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=网络安全">网络安全</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=电子商务">电子商务</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=硬件开发">硬件开发</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=数据库">数据库</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=程序设计">程序设计</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=人工智能">人工智能</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=算法">算法</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=编程语言">编程语言</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">哲学</div>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=东方哲学">东方哲学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=西方哲学">西方哲学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=哲学史">哲学史</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=马克思">马克思</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=逻辑学">逻辑学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=伦理学">伦理学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=美学">美学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=宗教">宗教</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">科技</div>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=机械">机械</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=建筑">建筑</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=电子通信">电子通信</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=化学">化学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=物理">物理</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=水利">水利</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=能源与动力">能源与动力</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=生物医学">生物医学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=矿业与冶炼">矿业与冶炼</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">社会</div>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=经济">经济</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=管理">管理</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=心理">心理</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=商务实务">商务实务</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=财政税收">财政税收</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=银行与货币">银行与货币</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">考研</div>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=考研数学">考研数学</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=考研英语">考研英语</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=考研政治">考研政治</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=考研计算机">考研计算机</a>
        </li>
    </ul>
    <div class="line"></div>
    <ul class="ul-container">
        <li class="literature-wrap">
            <div class="literature">青年</div>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=玄幻">玄幻</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=言情">言情</a>
        </li>
        <li>
            <a href="{% url 'showVideo' %}?search=侦探">侦探</a>
        </li>
    </ul>
    </div>
</div>