BACK/VAB/Usergroup/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from Usergroup import views

app_name = 'Usergroup'

urlpatterns = [
    path('', views.showGroup, name='showGroup'),
    path('<int:id>',views.GroupDetail, name='Groupdetail'),
    path('create',views.GroupCreate.as_view(), name='GroupCreate'),
    path('mygroup',views.MyGroupList,name='MyGroups'),
    path('join/<int:id>',views.JoinGroup,name='JoinGroup'),
    path('exit/<int:id>',views.ExitGroup,name='ExitGroup'),
    path('agreeAsk/<int:id>/',views.AgreeAsk,name='AgreeAsk'),
    path('refuseAsk/<int:id>/',views.RefuseAsk,name='RefuseAsk'),
    path('topArticle/<int:id>/<int:article_id>',views.topArticle,name='topArtilce'),
]

BACK/VAB/Userprofile/urls.py
from django.urls import re_path, path
from django.conf.urls import url
from Userprofile import views

app_name = 'Userprofile'

urlpatterns = [
    path('', views.loadHomepage, name='loadHomepage'),
    path('register/', views.register, name='register'),
    path('login/', views.userlogin, name='login'),
    path('Userprofile/<int:id>/profile/', views.profile, name='profile'),
    path('Userprofile/<int:id>/profile/update/', views.profile_update, name='profile_update'),
    path('Userprofile/<int:id>/pwd_change/', views.pwd_change, name='pwd_change'),
    path('logout/', views.userlogout, name='logout'),
    path('registerajax/',views.registerajax,name='registerajax'),
    path('checkusers/',views.checkusers,name='checkusers'),
    path('checkusers_login/',views.checkusers_login,name='checkusers_login'),
    path('checkemail/',views.checkemail,name='checkemail'),
    path('checkpwd/',views.checkpwd,name='checkpwd'),
    path('checkpwd_login/', views.checkpwd_login, name='checkpwd_login'),
]

BACK/VAB/VAB/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
import notifications.urls

urlpatterns = [
    # 用户管理
    path('admin/', admin.site.urls),

    # 图书管理
    path('book/', include('Books.urls')),

    # 视频管理
    path('video/',include('Videos.urls')),
    
    # 用户个人信息
    path('',include('Userprofile.urls')),

    # 评论管理
    path('comment/',include('comment.urls')),

    # 帖子管理
    path('article/',include('article.urls')),

    # 通知信息
    path('inbox/notifications/',include(notifications.urls,namespace='notifications')),

    path('notice/',include('notice.urls',namespace='notice')),

    # 小组信息
    path('group/',include('Usergroup.urls',namespace='group')),

    # 举报
    path('report/',include('report.urls',namespace='report')),

    # 申请
    path('ask/',include('askManage.urls',namespace='ask')),

    # 话题
    path('topic/',include('topic.urls',namespace='topic')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

BACK/VAB/askManage/urls.py
from django.urls import path
from . import views

app_name = 'ask'

urlpatterns = [
    path('ask-Formanage/<int:id>/',views.makeAsk,name='makeAsk'),
    path('allMyasks/<int:id>/',views.allMyask,name='allMyasks'),
    path('need-handle-asks/<int:id>/',views.handleAsk,name='NeedHandleAsks'),
]

BACK/VAB/Usergroup/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from article.models import Article

class Usergroup(models.Model):
    # 小组名称
    groupname = models.CharField(max_length=100)

    # 组长
    groupMaster = models.ForeignKey(User, on_delete=models.CASCADE, related_name='groupmaster')

    # 多对多的小组成员
    members = models.ManyToManyField(User,related_name='members')

    # 小组管理员
    group_managers = models.ManyToManyField(User,related_name='managers')

    # 小组创建日期
    createdTime = models.DateTimeField(default=timezone.now)

    # 小组成员数量
    groupsize = models.IntegerField(default=1)

    # 小组头像
    group_img = models.ImageField(upload_to='groupimg', null=True)

    # 小组简介
    group_info = models.TextField(max_length=1000,blank=True)

    # 置顶帖子
    top_article = models.ForeignKey(
        Article,
        on_delete=models.DO_NOTHING,
        blank=True,
        null=True
    )

BACK/VAB/Usergroup/forms.py
from django import forms
from .models import Usergroup

class GroupForm(forms.ModelForm):
    class Meta:
        model = Usergroup
        fields = ('groupname','group_img','group_info')

BACK/VAB/Usergroup/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse

from django.contrib.auth.models import User
from django.core.paginator import Paginator
from django.contrib.auth.decorators import login_required
from django.views import View
from .forms import GroupForm

from django.contrib.auth.decorators import login_required
from django.utils.decorators import method_decorator

from django.db.models import Q

from .models import Usergroup
from Userprofile.models import UserProfile
from article.models import Article
from askManage.models import Ask

# 小组列表（展示目前所有小组）
def showGroup(request):
    search = request.GET.get('search')

    allgroups = Usergroup.objects.all().order_by('-groupsize')

    if search:
        group_list = Usergroup.objects.all().order_by('-groupsize').filter(
            Q(groupname__icontains=search) |
            Q(group_info__icontains=search)
        )
    else:
        search = ''
        group_list = Usergroup.objects.all().order_by('-groupsize')

    paginator = Paginator(group_list, 4)
    page = request.GET.get('page')
    groups = paginator.get_page(page)

    if group_list.count() < 3:
        recommend_list = None
    else:
        recommend_list = [group_list[0], group_list[1],group_list[2]]

    context = {
        'groups':groups,
        'search': search ,
        'group_list':group_list,
        'groupcount':len(Usergroup.objects.all()),
        'recommend_list':recommend_list
    }

    return render(request, 'Usergroup/showGroups.html', context)


# 显示小组具体信息
def GroupDetail(request,id):
    # 小组的基本信息
    group = Usergroup.objects.get(id=id)
    members = group.members.all()
    master = group.groupMaster

    user_state = 0 # 默认游客状态
    is_member = group.members.filter(id=request.user.id).exists()
    is_manager = group.group_managers.filter(id=request.user.id).exists()
    is_master = (group.groupMaster.id == request.user.id)

    if is_member:
        user_state = 1 # 普通成员状态
        if is_manager:
            user_state = 2 # 管理员状态
            if is_master:
                user_state = 3 # 群主

    articles = []
    membersProfile = []
    # 找出小组成员的帖子
    for person in members:
        articles.extend(Article.objects.filter(author_id__exact=person.id))
        membersProfile.extend(UserProfile.objects.filter(user_id=person.id))


    context = {'group':group,'members':members,'master':master,'articles':articles,'profiles':membersProfile,'user_state':user_state}
    return render(request, 'Usergroup/GroupDetail.html',context)

# 创建小组
@method_decorator(login_required, name='post')
class GroupCreate(View):
    form_class = GroupForm
    initial = {}
    template_name = 'Usergroup/CreateGroup.html'

    def get(self, request, *args, **kwargs):
        form = self.form_class(initial=self.initial)
        return render(request, self.template_name, {'form': form})

    def post(self, request, *args, **kwargs):
        form = self.form_class(request.POST, request.FILES)

        if form.is_valid():
            groupname = form.cleaned_data['groupname']
            master = User.objects.get(id=request.user.id)
            groupinfo = form.cleaned_data['group_info']
            groupimg = request.FILES.get('group_img')
            groupsize = 1
            group = Usergroup.objects.create(
                groupname=groupname,
                groupMaster=master,
                group_info=groupinfo,
                groupsize=groupsize,
                group_img=groupimg
            )
            group.members.add(master)
            group.group_managers.add(master)
            group.save()

            return redirect("Usergroup:Groupdetail",id=group.id)
        else:
            print("Group:error!")
        return render(request, self.template_name, {'form':form})


# 查询自己所在小组
def MyGroupList(request):
    user_me = User.objects.get(id=request.user.id)
    mygroups = user_me.members.all()

    context = {'mygroups':mygroups}
    return render(request, 'Usergroup/MyGroups.html', context)


# 加入小组
def JoinGroup(request,id):
    group = Usergroup.objects.get(id=id)

    memberset = group.members.all()

    if memberset.filter(id=request.user.id):
        return HttpResponse("您已经在小组中了")
    else:
        person = User.objects.get(id=request.user.id)
        group.groupsize += 1
        group.members.add(person)
        group.save()
        return redirect('group:Groupdetail',id=id)

# 同意成为管理员
def AgreeAsk(request,id):
    ask = Ask.objects.get(id=id)
    group = ask.group
    asker = ask.asker
    group.group_managers.add(asker)
    group.save()

    # 完成处理
    ask.state = 2
    ask.save()

    return redirect('ask:NeedHandleAsks',id=request.user.id)

# 拒绝成为管理员
def RefuseAsk(request,id):
    ask = Ask.objects.get(id=id)
    ask.state = 1
    ask.save()

    return redirect('ask:NeedHandleAsks',id=request.user.id)


# 退出小组
def ExitGroup(request,id):
    # 组长退群 -- 删除小组
    group = Usergroup.objects.get(id=id)
    master = group.groupMaster

    if master.id == request.user.id:
        Usergroup.objects.filter(id=id).delete()
        return redirect('group:showGroup')
    # 成员退群
    else:
        memberset = group.members.all()
        managers = group.group_managers.all()

        if managers.filter(id=request.user.id).exists():
            userme = User.objects.all().get(id=request.user.id)
            group.group_managers.remove(userme)
            group.groupsize -= 1
            group.members.remove(userme)
            group.save()
            return redirect('group:showGroup')

        if memberset.filter(id=request.user.id).exists():
            userme = User.objects.all().get(id=request.user.id)
            group.groupsize -= 1
            group.members.remove(userme)
            group.save()
            return redirect('group:showGroup')
        else:
            return HttpResponse("您还没有加入小组")

# 置顶帖子
def topArticle(request,id,article_id):
    article = Article.objects.get(id=article_id)
    group = Usergroup.objects.get(id=id)

    group.top_article = article
    group.save()

    return redirect('group:Groupdetail',group.id)

BACK/VAB/templates/Usergroup/GroupDetail.html
{% load static %}
{% include 'topbar.html' %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
    <link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/topbar_style.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/groupListPage.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/posting_1.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/groupmain.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/groupmembers.css' %}">
    <title>{{ group.groupname }}的页面</title>
</head>
    <main>
        <div class="main01">
            <div class="a01">
                <div class="grouprightcon" id="a01">
                    <div class="groupright01">
                        <div class="grouprightimgcon">
                            <img src="{{ group.group_img.url }}" alt="" class="grouprightimg">
                        </div>
                        <div class="grouprighttextcon">
                            <a href="#" class="grouprightnamecon">
                                <div class="grouprightname">{{ group.groupname }}</div>
                            </a>
                            <div class="grouprightintro" style="margin-left: 40px;margin-top: 0px">
                                {{ group.groupsize }}个成员
                            </div>
                            <div style="width: 300px;margin-top: 20px;margin-left: 40px">
                            {% if user.is_authenticated %}
                                {% if user_state == 0 %}
                                    <a href="{% url 'Usergroup:JoinGroup' group.id %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-danger">加入小组</button>
                                    </a><br>
                                {% elif user_state == 1 %}
                                    <a href="{% url 'ArticleCreate' %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-success">推帖子</button>
                                    </a>
                                    <a href="{% url 'Usergroup:ExitGroup' group.id %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-secondary">退出小组</button>
                                    </a>
                                    <a href="{% url 'ask:makeAsk' group.id %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-info">申请管理员</button>
                                    </a>
                                {% elif user_state == 2 %}
                                    <a href="{% url 'ArticleCreate' %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-success">推帖子</button>
                                    </a>
                                    <a href="{% url 'Usergroup:ExitGroup' group.id %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-warning">退出小组</button>
                                    </a>
                                {% else %}
                                    <a href="{% url 'ArticleCreate' %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-success">推帖子</button>
                                    </a>
                                    <a href="{% url 'Usergroup:ExitGroup' group.id %}" style="display: inline-block">
                                        <button type="button" class="btn btn-outline-dark">解散小组</button>
                                    </a>
                                {% endif %}
                            {% else %}
                                <a href="{% url 'Userprofile:login' %}" style="display: inline-block">
                                    <button type="button" class="btn btn-outline-info">登录</button>
                                </a>
                            {% endif %}
                            </div>
                        </div>
                    </div>
                </div>
            </div><br>
            <div style="border: 2px dashed #ff7d79;width: 100px;height: 30px;border-top-right-radius: 10px;border-top-left-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 10px;background: #fff0eb">
                <div style="height: 100px;margin-left: 5px;margin-top: 5px">置顶帖子：</div>
            </div>
        {% if group.top_article %}
            <div class="posting_1">
                    <div class="outer" style="background: #ffdedf">
                        <div class="title">
                            <a href="{% url 'ArticleDetail' group.top_article.id %}"><h2>{{ group.top_article.title }}</h2></a><hr>
                            <div class="z">
                                <span>{{ group.top_article.column }}</span>
                            </div>
                            <div class="zz">发布人：<span>{{ group.top_article.author.username }}</span></div>
                            <div class="zzz">浏览数：<span>{{ group.top_article.total_views }}</span></div>
                            <div class="zz">发布时间：<span>{{ group.top_article.created }}</span></div>
                        </div>
                        <!-- 设置内容简介 -->
                        <div class="intro">
                            <p>
                                {{ group.top_article.body|slice:70 }}...
                            </p>
                        </div>
                        <div class="tag" style="margin-left: 70%;margin-top: -30%;border: 2px dashed red;border-top-right-radius: 10px;border-top-left-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 10px;">
                            <ul>
                                {% if group.top_article.tags.all.count == 0 %}
                                    <li><a href="#">暂无标签</a></li>
                                {% else %}
                                    {% for tag in group.top_article.tags.all %}
                                        <li><a href="#">{{ tag }}</a></li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% else %}
            <br>
                <div class="alert alert-danger" role="alert">
                    暂无置顶
                </div>
            {% endif %}
            <hr>
            {% for article in articles %}
                {% if user_state > 1 %}
                    <div style="border: 1px dashed red;width: 200px;height: 50px;border-top-right-radius: 10px;border-top-left-radius: 10px;border-bottom-right-radius: 10px;border-bottom-left-radius: 10px;">
                        <div style="margin-top: 15px;margin-left: 8px">
                            <a href="{% url 'GroupDeletePost' group.id article.id %}" style="display: inline-block">删除本帖</a>&nbsp;&nbsp;&nbsp;|&nbsp;&nbsp;&nbsp;
                            <a href="{% url 'group:topArtilce' group.id article.id %}" style="display: inline-block">置顶本贴</a>
                        </div>
                    </div>
                {% endif %}
                <div class="posting_1">
                    <div class="outer">
                        <div class="title">
                            <a href="{% url 'ArticleDetail' article.id %}"><h2>{{ article.title }}</h2></a>
                            <div class="z">
                                <span>{{ article.column }}</span>
                            </div>
                            <div class="zz">发布人：<span>{{ article.author.username }}</span></div>
                            <div class="zzz">浏览数：<span>{{ article.total_views }}</span></div>
                            <div class="zz">发布时间：<span>{{ article.created }}</span></div>
                        </div>
                        <!-- 设置内容简介 -->
                        <div class="intro">
                            <p>
                                {{ article.body|slice:70 }}...
                            </p>
                        </div>
                        <div class="tag" style="margin-left: 70%;margin-top: -30%">
                            <ul>
                                {% if article.tags.all.count == 0 %}
                                    <li><a href="#">暂无标签</a></li>
                                {% else %}
                                    {% for tag in article.tags.all %}
                                        <li><a href="#">{{ tag }}</a></li>
                                    {% endfor %}
                                {% endif %}
                            </ul>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="main02">
            <div class="peo">
                <div class="headman">
                    <a href="{% url 'Userprofile:profile' group.groupMaster.id %}">
                        组长:<span></span>{{ group.groupMaster.username }}
                    </a>
                </div>
                <nav>
                    <h2>小组成员(<span>{{ group.groupsize }}</span>)</h2>
                     <input id="toggle" type="checkbox" checked>
                      <ul style="height: auto;">
                          {% for one in profiles %}
                              <li>
                                  <a href="{% url 'Userprofile:profile' one.user.id %}">
                                      {{ one.user.username }}
                                  </a>
                              </li>
                          {% endfor %}
                      </ul>
               </nav>
                <div class="headman" style="margin-top: 60px">
                    <a href="#">
                        我的状态:<span></span>{% if user_state == 0 %}游客/非组员{% elif user_state == 1%}普通组员{% elif user_state == 2 %}管理员{% else %}组长{% endif %}
                    </a>
                </div>
            </div>
        </div>
    </main>
</html><br><br><br><br><br><br><br><br><br>
{% include 'footer.html' %}

BACK/VAB/templates/Usergroup/showGroups.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>小组列表</title>
    <link rel="stylesheet" href="{% static '/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static '/css_remove/reset.css' %}">
    <link rel="stylesheet" href="{% static '/iconfont/iconfont.css' %}">
    <link rel="stylesheet" href="{% static '/css_style/topbar_style.css' %}">
    <link rel="stylesheet" href="{% static 'css_style/groupListPage.css' %}">
    <link rel="stylesheet" href="{% static 'css_style/book_page.css' %}">
</head>
<style>
    .grouppage{
        width: 700px;
        height:40px;
        line-height: 40px;
        margin:50px auto;
        /* background-color: rgb(216, 209, 200); */
        display:flex;
        justify-content:space-between
    }
    .grouppage > li{
        /* flex-grow: 1; */
        justify-content:space-between
    }
    .grouppage a{
        display:block;
        width: 40px;
        height: 40px;
        border: rgb(194, 193, 193) 2px solid;
        color: rgb(119, 118, 117);
        text-decoration: none;
        text-align: center;
        border-radius: 10px;
    }
    /* 设置图标 */
    .grouppage .left,
    .grouppage .omit,
    .grouppage.right{
        font-size: 17px;
        font-weight: bolder;
    }
    /* 设置省略号 */
    .grouppage .omit{
        border:unset;
        margin-top:15px;
    }
    /* 设置竖线 */
    .grouppage .line{
        width: 1px;
        height: 35px;
        background-color: rgba(194, 193, 193,.7);
        margin-top: 5px;
        margin-left: 20px;
        margin-right: 20px;
    }
    /* 设置goto */
    .grouppage .goto{
        color: rgb(119, 118, 117);
        font-weight: bold;
        font-size: 18px;
    }
    /* 设置表单 */
    .grouppage div{
        width: 50px;
        border:  rgb(194, 193, 193) 2px solid;
        line-height: 30px;
        border-radius: 10px;
        /* background-color: thistle; */
    }
    .grouppage .page{
        width: 46px;
        border:unset;
        border-radius: 10px;
        line-height: 30px;
        text-align: center;
        outline: none;
        /* background-color: turquoise; */
    }
    /* 设置点击效果 */
    .grouppage a:not(.omit):hover{
        color:tomato;
        border: tomato 2px solid;
        transition: all .25s;
    }
</style>
{% include 'topbar.html' %}
<body>
    <main>
        <div class="main01">
            <div class="navigate01 iconfont"><span>&#xe626;</span> 所有小组</div>
            <ul class="topbook-wrap">
                <div class="find-wrap">
                    <form action="" class="find">
                        <input type="text" class="find-inp" placeholder="搜索" name="search" required>
                        <button class="find-btn">
                            <i class="iconfont find-icon">&#xe61c;</i>
                        </button>
                    </form>
                </div>
            </ul>
{#            <div class="commentline"></div>#}
            <br><br>
            {% if search %}
                {% if groups %}
                    <div class="alert alert-danger" role="alert">
                        <h4><span style="color: red">"{{ search }}"</span>的搜索结果如下：</h4>
                    </div>
                {% else %}
                    <div class="alert alert-danger" role="alert">
                      <h4>暂无<span style="color: red">"{{ search }}"</span>有关的小组</h4>
                    </div>
                {% endif %}
            {% endif %}

            {% if group_list.count > 0 %}
                {% for onegroup in groups %}
                    <div class="commentcon">
                        <div class="textimgcon">
                            <div class="commentname">
                                <a href="{% url 'group:Groupdetail' onegroup.id %}">
                                    {{ onegroup.groupname }}
                                </a>小组人数：{{ onegroup.groupsize }}
                            </div>
                            <div class="commentmain">
                                <div class="commentimgcon">
                                    <img src="{{ onegroup.group_img.url }}" alt="" class="commentimg" style="border: 2px solid #ffc7bb">
                                </div>
                                <div class="commenttext">
                                    {{ onegroup.group_info|slice:150 }}...
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="commentline"></div>
                {% endfor %}
            {% elif not search %}
                <div>还没有小组哦~</div>
            {% endif %}
        </div>
        <div class="main02">
            <div class="recommend iconfont"><span>&#xe63b;</span> 推荐加入的小组</div>
            {% if recommend_list is None %}
                <br><br><br>
                <div class="alert alert-secondary" role="alert">
                暂无推荐小组，去<a href="#" style="display:inline-block;">所有小组</a>看看吧
                </div>
            {% else %}
                {% for recommend in recommend_list %}
                    <div class="grouprightcon">
                        <div class="grouprightline"></div>
                        <div class="groupright01">
                            <div class="grouprightimgcon">
                                <img src="{{ recommend.group_img.url }}" alt="" class="grouprightimg" style="border: 2px dashed #ff7d79">
                            </div>
                            <div class="grouprighttextcon">
                                <a href="{% url 'group:Groupdetail' recommend.id %}" class="grouprightnamecon">
                                    <div class="grouprightname">{{recommend.groupname}}</div>
                                </a>
                                <div class="grouprightintro">
                                    {{ recommend.groupsize }}个成员
                                    {% if user.is_authenticated %}
                                    <button type="button" class="btn btn-outline-danger">
                                        <a href="{% url 'group:JoinGroup' recommend.id %}">+加入小组</a>
                                    </button>
                                    {% endif %}
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
                <a href="{% url 'Userprofile:loadHomepage' %}" class="morerecommendgroupcon">
                    <div class="morerecommendgroup01">查看更多>></div>
                </a>
            {% endif %}
        </div>

        <div class="pagenum-wrap" style="margin-left: -90%;margin-top: 80%;height: 40px;">
        <br><br><br><br><br><br><br><br><br><br><br>
            <li class="grouppage">
                {% if groups.has_previous %}
                        <a href="?page={{ groups.previous_page_number }}&search={{ search }}" class="iconfont left">&laquo;</a>
                    {% if  groups.number != 2 %}
                            <a href="?page=1&search={{ search }}">1</a>
                    {% endif %}

                    {% if  groups.number > 3 %}
                        &nbsp;&nbsp;&nbsp;...&nbsp;&nbsp;&nbsp;
                    {% endif %}

                    <a href="?page={{ groups.previous_page_number }}&search={{ search }}">
                        {{ groups.previous_page_number }}
                    </a>
                {% endif %}
                    <a href="#" style="background: #ffb5ae">{{ groups.number }}</a>
                {% if groups.has_next %}
                    {% if groups.number|add:1 < groups.paginator.num_pages %}
                        <a href="?page={{ groups.next_page_number }}&search={{ search }}">
                            {{ groups.next_page_number }}
                        </a>
                    {% endif %}
                    {% if groups.number|add:2 < groups.paginator.num_pages%}
                        <span>&nbsp;&nbsp;&nbsp;...&nbsp;&nbsp;&nbsp;</span>
                    {% endif %}

                    <a href="?page={{ groups.paginator.num_pages }}&search={{ search }}">
                        {{ groups.paginator.num_pages }}
                    </a>
                    <a href="?page={{ groups.next_page_number }}&search={{ search }}" class="iconfont right">&raquo;</a>
                {% endif %}
            </li>
        </div>
    </main>
</body>
</html>
<div style="height: 200px"></div>
{% include 'footer.html' %}